[package]
name = "ligen-core"
version = "0.1.0"
authors = ["Danilo Guanabara <danguafer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.1"
syn = { version = "1.0.2", features = [ "full" ] }
quote = "1.0"
libloading = "0.5"
